# Generated by Django 4.2.2 on 2023-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('OpNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('PatientName', models.TextField(max_length=255)),
                ('Weight', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(max_length=20)),
                ('Address', models.TextField(max_length=500)),
                ('AdmissionDate', models.DateField()),
            ],
        ),
    ]
