# Generated by Django 4.2.2 on 2023-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='Sex',
            field=models.TextField(max_length=255),
        ),
    ]
