# Generated by Django 4.2.2 on 2023-06-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0002_alter_patients_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='AdmissionDate',
        ),
    ]
