# Generated by Django 4.2.2 on 2023-06-18 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0003_remove_patients_admissiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='AdmissionDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
